######################################################################
# Automatically generated by qmake (3.1) Thu Feb 16 15:00:45 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = l01_HelloQt
INCLUDEPATH += .

# Input
SOURCES += main.cpp
